# Generated by Django 5.1.6 on 2025-05-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='bird',
            field=models.ForeignKey(default='', help_text='Select the species you observed in this Sighting', on_delete=django.db.models.deletion.CASCADE, to='bofz.bird'),
        ),
    ]
