# Generated by Django 5.1.6 on 2025-04-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='date',
            new_name='datetime',
        ),
    ]
