# Generated by Django 5.1.6 on 2025-05-12 18:06

import bofz.models.person
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(default=bofz.models.person.Person.get_default_pk, help_text='Who took this Photo?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='observers',
            field=models.ManyToManyField(help_text='Who observed these birds?', to=settings.AUTH_USER_MODEL),
        ),
    ]
