# Generated by Django 5.1.6 on 2025-04-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0002_rename_date_sighting_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.TextField(verbose_name="The scientific name of their genus, e.g. 'Anthropoides'")),
                ('species', models.TextField(verbose_name="The scientific name of their species, usually lowercase. e.g. 'paradiseus'")),
                ('family', models.TextField(verbose_name="Common name of this species' family or grouping, e.g. 'Crane'")),
                ('common_identifier', models.TextField(verbose_name="Common identifier in this species' family or grouping, e.g. 'Blue'")),
                ('afrikaans_name', models.TextField(verbose_name="Afrikaans common name for this species, e.g. 'Blou Kraanvoël'")),
                ('german_name', models.TextField(verbose_name="German common name for this species, e.g. 'Paradieskranich'")),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Their full name')),
                ('short_name', models.TextField(verbose_name='What should we call them?')),
                ('email', models.EmailField(max_length=254, verbose_name='Used as their username, and our way of staying in contact')),
            ],
        ),
    ]
