# Generated by Django 5.1.6 on 2025-05-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0002_alter_sighting_bird'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bird',
            options={'ordering': ['family', 'common_name']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='sighting',
            options={'ordering': ['-datetime']},
        ),
    ]
