# Generated by Django 5.1.6 on 2025-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0003_bird_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='afrikaans_name',
            field=models.TextField(db_comment="Afrikaans common name for this species, e.g. 'Blou Kraanvoël'", verbose_name='Afrikaans name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='common_identifier',
            field=models.TextField(db_comment="Common identifier in this species' family or grouping, e.g. 'Blue'", verbose_name='Family identifier'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='family',
            field=models.TextField(db_comment="Common name of this species' family or grouping, e.g. 'Crane'", verbose_name='Family name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='genus',
            field=models.TextField(db_comment="The scientific name of their genus, e.g. 'Anthropoides'", verbose_name='Genus'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='german_name',
            field=models.TextField(db_comment="German common name for this species, e.g. 'Paradieskranich'", verbose_name='German name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='species',
            field=models.TextField(db_comment="The scientific name of their species, usually lowercase. e.g. 'paradiseus'", verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(db_comment='Used as their username, and our way of staying in contact', max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.TextField(db_comment='Their full name, avoids problems with first, last, family, and surnames', verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='short_name',
            field=models.TextField(db_comment='What should we call them?', verbose_name='Short name'),
        ),
    ]
