# Generated by Django 5.1.6 on 2025-04-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0004_alter_bird_afrikaans_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='afrikaans_name',
            field=models.CharField(db_comment="Afrikaans common name for this species, e.g. 'Blou Kraanvoël'", max_length=64, verbose_name='Afrikaans name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='common_identifier',
            field=models.CharField(db_comment="Common identifier in this species' family or grouping, e.g. 'Blue'", max_length=32, verbose_name='Family identifier'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='family',
            field=models.CharField(db_comment="Common name of this species' family or grouping, e.g. 'Crane'", max_length=32, verbose_name='Family name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='genus',
            field=models.CharField(db_comment="The scientific name of their genus, e.g. 'Anthropoides'", max_length=64, verbose_name='Genus'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='german_name',
            field=models.CharField(db_comment="German common name for this species, e.g. 'Paradieskranich'", max_length=64, verbose_name='German name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='species',
            field=models.CharField(db_comment="The scientific name of their species, usually lowercase. e.g. 'paradiseus'", max_length=64, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(db_comment='Used as their username, and our way of staying in contact', max_length=64, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(db_comment='Their full name, avoids problems with first, last, family, and surnames', max_length=32, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='short_name',
            field=models.CharField(db_comment='What should we call them?', max_length=16, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='datetime',
            field=models.DateTimeField(db_comment="We need a to-the-minute recording of the sighting. We can potentially infer this from any supporting photos' EXIF data.", verbose_name='Date and time of sighting'),
        ),
    ]
