# Generated by Django 5.1.6 on 2025-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0005_alter_bird_afrikaans_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedListLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveIntegerField(db_comment='How severe is this level?', help_text='Where 1 = CR/Critically endangered and 6 = LC/Least Concern', verbose_name='Severity rank')),
                ('abbreviation', models.CharField(db_comment='The abbreviated form of this RedList level', help_text='2 characters or less', max_length=2, verbose_name='Abbreviation')),
                ('label', models.CharField(db_comment='The longer form of the abbreviation', help_text='The human readable name for this RedList level', max_length=32, verbose_name='Label')),
            ],
        ),
        migrations.RemoveField(
            model_name='bird',
            name='common_identifier',
        ),
        migrations.AddField(
            model_name='bird',
            name='common_name',
            field=models.CharField(db_comment="English common name for this species. e.g. 'Blue Crane'", default='', help_text='e.g. Blue Crane', max_length=64, verbose_name='Common name'),
        ),
        migrations.AddField(
            model_name='bird',
            name='ebird',
            field=models.URLField(db_comment='Useful as a reference for this bird', help_text='e.g. https://ebird.org/species/blucra2/ZA', max_length=64, null=True, verbose_name='eBird URL'),
        ),
        migrations.AddField(
            model_name='bird',
            name='wikipedia',
            field=models.URLField(db_comment='Useful as a reference for this bird', help_text='e.g. https://en.wikipedia.org/wiki/Blue_crane', max_length=64, null=True, verbose_name='Wikipedia URL'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='afrikaans_name',
            field=models.CharField(db_comment="Afrikaans common name for this species, e.g. 'Blou Kraanvoël'", help_text='e.g. Blou Kraanvoël', max_length=64, null=True, verbose_name='Afrikaans name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='family',
            field=models.CharField(default='', help_text="Common name of this species' family or grouping, e.g. 'Crane'", max_length=32, verbose_name='Family name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='genus',
            field=models.CharField(default='', help_text="The scientific name of their genus, e.g. 'Anthropoides'", max_length=64, verbose_name='Genus'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='german_name',
            field=models.CharField(db_comment="German common name for this species, e.g. 'Paradieskranich'", help_text='e.g. Paradieskranich', max_length=64, null=True, verbose_name='German name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='species',
            field=models.CharField(default='', help_text="The scientific name of their species, usually lowercase. e.g. 'paradiseus'", max_length=64, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text='Used as their username, and our way of staying in contact', max_length=64, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(help_text='Their full name, avoids problems with first, last, family, and surnames', max_length=32, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='short_name',
            field=models.CharField(help_text='What should we call them?', max_length=16, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='datetime',
            field=models.DateTimeField(help_text="We need a to-the-minute recording of the sighting. We can potentially infer this from any supporting photos' EXIF data.", verbose_name='Date and time of sighting'),
        ),
    ]
