# Generated by Django 5.1.6 on 2025-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0006_redlistlevel_remove_bird_common_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redlistlevel',
            name='severity',
            field=models.PositiveIntegerField(db_comment='How severe is this level?', help_text='Where 1 = CR/Critically endangered and 5 = LC/Least Concern', verbose_name='Severity rank'),
        ),
    ]
