# Generated by Django 5.1.6 on 2025-04-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0008_bird_redlist_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redlistlevel',
            options={'ordering': ['severity']},
        ),
        migrations.AddField(
            model_name='sighting',
            name='observers',
            field=models.ManyToManyField(to='bofz.person'),
        ),
    ]
