# Generated by Django 5.1.6 on 2025-04-19 12:22

import bofz.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0009_alter_redlistlevel_options_sighting_observers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='bird',
            field=models.ForeignKey(default=bofz.models.Bird.get_default_pk, help_text='Select the species you observed in this Sighting', on_delete=django.db.models.deletion.CASCADE, to='bofz.bird'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='How many total individuals of this species were seen?', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(db_comment='Avoids problems with first, last, family, and surnames', help_text='Their full name', max_length=32, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='datetime',
            field=models.DateTimeField(db_comment="We need a to-the-minute recording of the time and date of this sighting. We can potentially infer this from any supporting photos' EXIF data.", help_text='What date and time was this sighting?', verbose_name='Date and time of sighting'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='observers',
            field=models.ManyToManyField(help_text='Who observed these birds?', to='bofz.person'),
        ),
    ]
