# Generated by Django 5.1.6 on 2025-04-20 15:21

import bofz.models.person
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0010_sighting_bird_sighting_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_comment='We need a to-the-minute recording of the time and date of this photo', help_text='What date and time was this photo?', verbose_name='Date and time of photo')),
                ('photographer', models.ForeignKey(default=bofz.models.person.Person.get_default_pk, help_text='Who took this Photo?', on_delete=django.db.models.deletion.CASCADE, to='bofz.person')),
            ],
        ),
        migrations.AddField(
            model_name='sighting',
            name='photos',
            field=models.ManyToManyField(help_text='Select the Photos associated with this Sighting', null=True, to='bofz.photo'),
        ),
    ]
