# Generated by Django 5.1.6 on 2025-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0011_photo_sighting_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='photos',
            field=models.ManyToManyField(blank=True, help_text='Select the Photos associated with this Sighting', to='bofz.photo'),
        ),
    ]
