# Generated by Django 5.1.6 on 2025-04-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0012_alter_sighting_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='afrikaans_name',
            field=models.CharField(blank=True, db_comment="Afrikaans common name for this species, e.g. 'Blou Kraanvoël'", default='', help_text='e.g. Blou Kraanvoël', max_length=64, verbose_name='Afrikaans name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='ebird',
            field=models.URLField(blank=True, db_comment='Useful as a reference for this bird', default='', help_text='e.g. https://ebird.org/species/blucra2/ZA', max_length=64, verbose_name='eBird URL'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='german_name',
            field=models.CharField(blank=True, db_comment="German common name for this species, e.g. 'Paradieskranich'", default='', help_text='e.g. Paradieskranich', max_length=64, verbose_name='German name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='wikipedia',
            field=models.URLField(blank=True, db_comment='Useful as a reference for this bird', default='', help_text='e.g. https://en.wikipedia.org/wiki/Blue_crane', max_length=64, verbose_name='Wikipedia URL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Used as their username, and our way of staying in contact', max_length=64, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(blank=True, db_comment='Avoids problems with first, last, family, and surnames', default='', help_text='Their full name', max_length=32, verbose_name='Full name'),
        ),
    ]
