# Generated by Django 5.1.6 on 2025-04-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0013_alter_bird_afrikaans_name_alter_bird_ebird_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='photographed',
            field=models.BooleanField(db_comment="We'll use this to determine the bird's visibility in lists and counts", default=False, help_text='Does this bird have any Photos associated with it?', verbose_name='Photographed'),
        ),
        migrations.AddField(
            model_name='bird',
            name='sighted',
            field=models.BooleanField(db_comment="We'll use this to determine the bird's visibility in lists and counts", default=False, help_text='Does this bird have any Sightings associated with it?', verbose_name='Sighted'),
        ),
    ]
