# Generated by Django 5.1.6 on 2025-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0014_bird_photographed_bird_sighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='potential',
            field=models.BooleanField(db_comment="This will mostly be driven by the bird's inclusion in a SpeciesList", default=False, help_text='Does this Bird have potential to be sighted in these Areas', verbose_name='Potential'),
        ),
        migrations.CreateModel(
            name='SpeciesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text="What is this list's name, or who supplied this list?", max_length=32, verbose_name='Name')),
                ('url', models.URLField(blank=True, db_comment='Any reference we can provide for this source is valuable', default='', help_text='The canonical reference of this list on the Web', max_length=64, verbose_name='URL or reference site')),
                ('author', models.CharField(db_comment='Identify the responsible authors of this list', default='', help_text='Which individual or group/organisation created this list?', max_length=32, verbose_name='Author or Organisation')),
                ('birds', models.ManyToManyField(help_text='All the birds contained in this list', to='bofz.bird')),
            ],
        ),
    ]
