# Generated by Django 5.1.6 on 2025-05-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0015_bird_potential_specieslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment="Helps identify the general area a sighting or photo will be bound by. Useful to obfuscate sightings taken from a Person's home.", default='', help_text='The name of this gated community, farm, or other', max_length=32, verbose_name='Name')),
                ('street', models.CharField(db_comment='Used with the suburb to build up a physical address', default='', help_text='What is the street name and number for the entrance to this Area?', max_length=32, verbose_name='Street name and number')),
                ('suburb', models.CharField(db_comment='Used with the street address to build up a physical address', default='Kuils River', help_text='What is the suburb or municipality of this Area', max_length=32, verbose_name='Suburb')),
                ('entrance', models.JSONField(help_text='What is the GPS location (in GeoJSON) of the entrance of this Area? Use https://geojson.io/', verbose_name='Entrance GeoJSON (GPS)')),
                ('centre', models.JSONField(help_text='Supply the GeoJSON of coordinates that are at the centre of the Area. Use https://geojson.io/', verbose_name='Centre (GeoJSON)')),
                ('boundaries', models.JSONField(help_text='Supply the GeoJSON of coordinates that create the outer boundary of the Area. Use https://geojson.io/', verbose_name='GeoJSON Fence or Boundary')),
            ],
        ),
    ]
