# Generated by Django 5.1.6 on 2025-05-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0016_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='boundaries',
            field=models.JSONField(help_text='Supply the GeoJSON of coordinates that creates the outer boundary of the Area. Use https://geojson.io/', verbose_name='Boundary (GeoJSON) or GeoFence'),
        ),
        migrations.AlterField(
            model_name='area',
            name='centre',
            field=models.JSONField(help_text='The GPS location (in GeoJSON) of the centre of this Area. Use https://geojson.io/', verbose_name='Centre (GeoJSON)'),
        ),
        migrations.AlterField(
            model_name='area',
            name='entrance',
            field=models.JSONField(help_text='The GPS location (in GeoJSON) of the entrance of this Area. Use https://geojson.io/', verbose_name='Entrance (GeoJSON)'),
        ),
    ]
