# Generated by Django 5.1.6 on 2025-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0017_alter_area_boundaries_alter_area_centre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='url',
            field=models.URLField(db_comment='Provides a reference link to the Area', help_text='Does this Area have a representative website?', max_length=64, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(db_comment="Helps identify the general area a sighting or photo will be bound by. Areas are useful to obfuscate sightings taken from a Person's home.", default='', help_text='The name of this gated community, farm, or other', max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='street',
            field=models.CharField(db_comment='Used with the suburb to build up a physical address', default='', help_text='What is the street name and number for the entrance to this Area?', max_length=32, null=True, verbose_name='Street name and number'),
        ),
        migrations.AlterField(
            model_name='area',
            name='suburb',
            field=models.CharField(db_comment='Used with the street address to build up a physical address', default='Kuils River', help_text='What is the suburb or municipality of this Area', max_length=32, null=True, verbose_name='Suburb'),
        ),
    ]
