# Generated by Django 5.1.6 on 2025-05-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0018_area_url_alter_area_name_alter_area_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specieslist',
            name='url',
            field=models.URLField(db_comment='Any reference we can provide for this source is valuable', help_text='The canonical reference of this list on the Web', max_length=64, null=True, verbose_name='URL or reference site'),
        ),
    ]
