# Generated by Django 5.1.6 on 2025-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0019_alter_specieslist_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exif_identifier', models.CharField(default='', help_text="The combination of manufacturer and model used in the Photo's EXIF data to identify this Camera, e.g. Canon-Canon EOS 500D", max_length=32, verbose_name='EXIF identifier')),
                ('manufacturer', models.CharField(default='', help_text="The name of the Camera's brand or manufacturer, e.g. Apple", max_length=32, verbose_name='Manufacturer')),
                ('model_name', models.CharField(default='', help_text="The name of the Camera's model, e.g. EOS 5D Mark II", max_length=32, verbose_name='Model')),
            ],
        ),
    ]
