# Generated by Django 5.1.6 on 2025-05-03 16:09

import bofz.models.photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0020_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='source_photo',
            field=models.ImageField(default='', upload_to=bofz.models.photo.person_id_folder_path, verbose_name='Source photo'),
        ),
    ]
