# Generated by Django 5.1.6 on 2025-05-03 16:41

import bofz.models.area
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0021_photo_source_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(db_comment='This plain text will act as alternative text for the image', default='', help_text='Describe this photo, as if you were describing it over the phone to someone', max_length=256, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='area',
            field=models.ForeignKey(default=bofz.models.area.Area.get_default_pk, help_text='Which Area was this Sighting recorded in?', on_delete=django.db.models.deletion.CASCADE, to='bofz.area'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='photos',
            field=models.ManyToManyField(help_text='Select the optional Photos associated with this Sighting', null=True, to='bofz.photo'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='quantity',
            field=models.PositiveIntegerField(db_comment='We need numbers of the species', default=1, help_text='How many total individuals of this species were seen?', verbose_name='Quantity'),
        ),
    ]
