# Generated by Django 5.1.6 on 2025-05-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofz', '0022_photo_description_sighting_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='photos',
            field=models.ManyToManyField(blank=True, help_text='Select the optional Photos associated with this Sighting', to='bofz.photo'),
        ),
    ]
